FROM apache/airflow:3.0.6-python3.12

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
 
USER root
RUN apt-get update

USER airflow
RUN pip install --upgrade pip \
    pip install domino-py[airflow]